# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-05-07 14:35
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='desc',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='商品详情'),
        ),
    ]
