# Generated by Django 2.0 on 2020-05-16 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20200516_1516'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shopcart',
            unique_together=set(),
        ),
    ]
