# Generated by Django 2.0 on 2020-05-16 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_auto_20200516_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='order_amount',
            new_name='order_mount',
        ),
        migrations.RenameField(
            model_name='orderinfo',
            old_name='signing_mobile',
            new_name='signer_mobile',
        ),
        migrations.RenameField(
            model_name='orderinfo',
            old_name='signing_name',
            new_name='signer_name',
        ),
    ]
