# Generated by Django 2.0 on 2020-05-16 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_auto_20200516_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='trade_status',
            new_name='pay_status',
        ),
    ]
