# Generated by Django 2.0 on 2020-05-16 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_auto_20200516_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordergoods',
            old_name='nums',
            new_name='goods_num',
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='trade.OrderInfo', verbose_name='所属订单'),
        ),
    ]
