# Generated by Django 2.0 on 2020-05-16 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_auto_20200513_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userleavingmessage',
            old_name='msg_type',
            new_name='message_type',
        ),
    ]
