# Generated by Django 2.0 on 2020-05-16 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_auto_20200516_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='signing_mobile',
            new_name='signer_mobile',
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='signing_name',
            new_name='signer_name',
        ),
    ]
